# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/34c2b734-2d34-4864-867e-4acd9f276acd";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/34c2b734-2d34-4864-867e-4acd9f276acd";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/34c2b734-2d34-4864-867e-4acd9f276acd";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/34c2b734-2d34-4864-867e-4acd9f276acd";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/lib/nixos" =
    { device = "/nix/@persist/var/lib/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/log" =
    { device = "/nix/@persist/var/log";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.mozilla" =
    { device = "/nix/@persist/home/shuntia/.mozilla";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.gnupg" =
    { device = "/nix/@persist/home/shuntia/.gnupg";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/etc/NetworkManager/system-connections" =
    { device = "/nix/@persist/etc/NetworkManager/system-connections";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.cache/nv" =
    { device = "/nix/@persist/home/shuntia/.cache/nv";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.local/share/Steam" =
    { device = "/nix/@persist/home/shuntia/.local/share/Steam";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.local/share/keyrings" =
    { device = "/nix/@persist/home/shuntia/.local/share/keyrings";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.cache/mesa_shader_cache" =
    { device = "/nix/@persist/home/shuntia/.cache/mesa_shader_cache";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/nix/@persist/etc/nixos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.ssh" =
    { device = "/nix/@persist/home/shuntia/.ssh";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/.steam" =
    { device = "/nix/@persist/home/shuntia/.steam";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Documents" =
    { device = "/nix/@persist/home/shuntia/Documents";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Downloads" =
    { device = "/nix/@persist/home/shuntia/Downloads";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Music" =
    { device = "/nix/@persist/home/shuntia/Music";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Pictures" =
    { device = "/nix/@persist/home/shuntia/Pictures";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Projects" =
    { device = "/nix/@persist/home/shuntia/Projects";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/shuntia/Videos" =
    { device = "/nix/@persist/home/shuntia/Videos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/NetworkManager" =
    { device = "/nix/@persist/var/lib/NetworkManager";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/systemd/coredump" =
    { device = "/nix/@persist/var/lib/systemd/coredump";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/bluetooth" =
    { device = "/nix/@persist/var/lib/bluetooth";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/tailscale" =
    { device = "/nix/@persist/var/lib/tailscale";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot.bak" =
    { device = "/dev/disk/by-uuid/8792-47A5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8818-828C";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/e34c9c01-9f99-43b7-9209-7214f316ef0d"; }
      { device = "/dev/disk/by-uuid/e770c398-f293-4a8d-9cdf-266f1cf0f52b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
